// <auto-generated />
using System;
using Kolokwium.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kolokwium.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    partial class EventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kolokwium.Models.Artist", b =>
                {
                    b.Property<int>("idArtist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nickname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idArtist");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Kolokwium.Models.Artist_Event", b =>
                {
                    b.Property<int>("idArtistEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("PerformanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("artistidArtist")
                        .HasColumnType("int");

                    b.Property<int>("idArtist")
                        .HasColumnType("int");

                    b.Property<int>("idEvent")
                        .HasColumnType("int");

                    b.HasKey("idArtistEvent");

                    b.HasIndex("artistidArtist");

                    b.HasIndex("idEvent");

                    b.ToTable("Artist_Events");
                });

            modelBuilder.Entity("Kolokwium.Models.Event", b =>
                {
                    b.Property<int>("idEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idEvent");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Kolokwium.Models.Event_Organiser", b =>
                {
                    b.Property<int>("idEventOrganiser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idEvent")
                        .HasColumnType("int");

                    b.Property<int>("idOrganiser")
                        .HasColumnType("int");

                    b.HasKey("idEventOrganiser");

                    b.HasIndex("idEvent");

                    b.HasIndex("idOrganiser");

                    b.ToTable("Event_Organisers");
                });

            modelBuilder.Entity("Kolokwium.Models.Organiser", b =>
                {
                    b.Property<int>("idOrganiser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrganiser");

                    b.ToTable("Organisers");
                });

            modelBuilder.Entity("Kolokwium.Models.Artist_Event", b =>
                {
                    b.HasOne("Kolokwium.Models.Artist", "artist")
                        .WithMany("artistEvents")
                        .HasForeignKey("artistidArtist");

                    b.HasOne("Kolokwium.Models.Event", "event_")
                        .WithMany("artistEvents")
                        .HasForeignKey("idEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kolokwium.Models.Event_Organiser", b =>
                {
                    b.HasOne("Kolokwium.Models.Event", "event_")
                        .WithMany("eventOrganisers")
                        .HasForeignKey("idEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Organiser", "organiser")
                        .WithMany("eventOrganisers")
                        .HasForeignKey("idOrganiser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
