// <auto-generated />
using System;
using Kolokwium2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kolokwium2.Migrations
{
    [DbContext(typeof(FireDbContext))]
    [Migration("20200704152229_powiazawniaPozostale")]
    partial class powiazawniaPozostale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kolokwium2.Models.Action", b =>
                {
                    b.Property<int>("idAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("needSpecialEquipment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idAction");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Kolokwium2.Models.FireTruck", b =>
                {
                    b.Property<int>("idFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("operationalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("specialEquipment")
                        .HasColumnType("bit");

                    b.HasKey("idFireTruck");

                    b.ToTable("FireTrucks");
                });

            modelBuilder.Entity("Kolokwium2.Models.FireTruckAction", b =>
                {
                    b.Property<int>("idFireTruckAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("assignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("idAction")
                        .HasColumnType("int");

                    b.Property<int>("idFireTruck")
                        .HasColumnType("int");

                    b.HasKey("idFireTruckAction");

                    b.HasIndex("idAction");

                    b.HasIndex("idFireTruck");

                    b.ToTable("FireTruckActions");
                });

            modelBuilder.Entity("Kolokwium2.Models.Firefighter", b =>
                {
                    b.Property<int>("idFirefighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("idFirefighter");

                    b.ToTable("Firefighters");
                });

            modelBuilder.Entity("Kolokwium2.Models.FirefighterAction", b =>
                {
                    b.Property<int>("idAction")
                        .HasColumnType("int");

                    b.Property<int>("idFirefighter")
                        .HasColumnType("int");

                    b.HasKey("idAction", "idFirefighter");

                    b.HasIndex("idFirefighter");

                    b.ToTable("FirefighterActions");
                });

            modelBuilder.Entity("Kolokwium2.Models.FireTruckAction", b =>
                {
                    b.HasOne("Kolokwium2.Models.Action", "Actions")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("idAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2.Models.FireTruck", "FireTrucks")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("idFireTruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kolokwium2.Models.FirefighterAction", b =>
                {
                    b.HasOne("Kolokwium2.Models.Action", "action")
                        .WithMany("firefighterActions")
                        .HasForeignKey("idAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2.Models.Firefighter", "firefighter")
                        .WithMany("firefighterActions")
                        .HasForeignKey("idFirefighter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
